/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as EquipmentIndexRouteImport } from './routes/equipment.index'
import { Route as EquipmentEquipmentIdRouteImport } from './routes/equipment.$equipmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIndexRoute = EquipmentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EquipmentRoute,
} as any)
const EquipmentEquipmentIdRoute = EquipmentEquipmentIdRouteImport.update({
  id: '/$equipmentId',
  path: '/$equipmentId',
  getParentRoute: () => EquipmentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipment': typeof EquipmentRouteWithChildren
  '/equipment/$equipmentId': typeof EquipmentEquipmentIdRoute
  '/equipment/': typeof EquipmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipment/$equipmentId': typeof EquipmentEquipmentIdRoute
  '/equipment': typeof EquipmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipment': typeof EquipmentRouteWithChildren
  '/equipment/$equipmentId': typeof EquipmentEquipmentIdRoute
  '/equipment/': typeof EquipmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/equipment' | '/equipment/$equipmentId' | '/equipment/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/equipment/$equipmentId' | '/equipment'
  id:
    '__root__' | '/' | '/equipment' | '/equipment/$equipmentId' | '/equipment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipmentRoute: typeof EquipmentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/': {
      id: '/equipment/'
      path: '/'
      fullPath: '/equipment/'
      preLoaderRoute: typeof EquipmentIndexRouteImport
      parentRoute: typeof EquipmentRoute
    }
    '/equipment/$equipmentId': {
      id: '/equipment/$equipmentId'
      path: '/$equipmentId'
      fullPath: '/equipment/$equipmentId'
      preLoaderRoute: typeof EquipmentEquipmentIdRouteImport
      parentRoute: typeof EquipmentRoute
    }
  }
}

interface EquipmentRouteChildren {
  EquipmentEquipmentIdRoute: typeof EquipmentEquipmentIdRoute
  EquipmentIndexRoute: typeof EquipmentIndexRoute
}

const EquipmentRouteChildren: EquipmentRouteChildren = {
  EquipmentEquipmentIdRoute: EquipmentEquipmentIdRoute,
  EquipmentIndexRoute: EquipmentIndexRoute,
}

const EquipmentRouteWithChildren = EquipmentRoute._addFileChildren(
  EquipmentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipmentRoute: EquipmentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
